import { Exam, StudentSession } from '@/types/exam';

export const INITIAL_EXAMS: Exam[] = [
  {
    id: 'exam-cs350-midterm',
    title: 'CS 350: Operating Systems & Systems Programming Midterm',
    courseCode: 'CS-350',
    description: 'Comprehensive assessment covering process concurrency, virtual memory, paging, CPU scheduling algorithms, and deadlock resolution.',
    durationMinutes: 45,
    totalPoints: 100,
    passingPercentage: 70,
    accessCode: 'OS-8821',
    status: 'active',
    createdAt: new Date(Date.now() - 3600000 * 24 * 2).toISOString(),
    professorName: 'Dr. Evelyn Martinez',
    professorEmail: 'emartinez@university.edu',
    securitySettings: {
      fullscreenEnforced: true,
      webcamRequired: true,
      audioMonitoring: true,
      blockCopyPaste: true,
      blockDevToolsAndShortcuts: true,
      tabSwitchDetection: true,
      faceTracking: true,
      gazeDetection: true,
      multiplePersonDetection: true,
      maxViolationsAllowed: 5,
      randomizeQuestions: false,
      randomizeOptions: true,
      requirePasscode: true,
      strictAutoSubmit: true,
    },
    sharingSettings: {
      publicLinkEnabled: true,
      accessCodeEnabled: true,
      qrCodeEnabled: true,
      embedCodeEnabled: true,
      customSlug: 'cs350-fall-midterm',
      passcode: 'SYS2026',
      scheduledStartTime: new Date(Date.now() - 3600000).toISOString(),
      scheduledEndTime: new Date(Date.now() + 3600000 * 24).toISOString(),
    },
    questions: [
      {
        id: 'q1',
        type: 'multiple_choice',
        prompt: 'Which of the following conditions is NOT one of Coffman\'s four necessary conditions for a deadlock to occur?',
        options: [
          { id: 'opt_a', text: 'Mutual Exclusion' },
          { id: 'opt_b', text: 'Hold and Wait' },
          { id: 'opt_c', text: 'Preemption Allowed' },
          { id: 'opt_d', text: 'Circular Wait' },
        ],
        correctAnswers: ['opt_c'],
        points: 20,
        explanation: 'Coffman\'s conditions require "No Preemption" (resources cannot be forcibly taken). If preemption is allowed, deadlock is eliminated.',
      },
      {
        id: 'q2',
        type: 'multiple_response',
        prompt: 'Select ALL memory management techniques that suffer from internal fragmentation:',
        options: [
          { id: 'opt_a', text: 'Fixed-size Partitioning' },
          { id: 'opt_b', text: 'Standard Paging (last page)' },
          { id: 'opt_c', text: 'Pure Variable Partitioning' },
          { id: 'opt_d', text: 'Pure Segmentation' },
        ],
        correctAnswers: ['opt_a', 'opt_b'],
        points: 25,
        explanation: 'Fixed partitioning allocates fixed chunks regardless of process size; paging also incurs internal fragmentation in the last page frame allocated.',
      },
      {
        id: 'q3',
        type: 'multiple_choice',
        prompt: 'In the context of the translation lookaside buffer (TLB), what occurs when a virtual address lookup is NOT present in the TLB cache?',
        options: [
          { id: 'opt_a', text: 'A segmentation fault terminates the process immediately' },
          { id: 'opt_b', text: 'A TLB miss triggers a page table walk in main memory' },
          { id: 'opt_c', text: 'The OS kernel swaps the process out to disk' },
          { id: 'opt_d', text: 'The CPU switches to hyperthreading mode' },
        ],
        correctAnswers: ['opt_b'],
        points: 25,
        explanation: 'A TLB miss forces a page table traversal (hardware or software walk) in RAM to locate the Physical Frame Number.',
      },
      {
        id: 'q4',
        type: 'short_answer',
        prompt: 'What POSIX system call creates a new process by duplicating the calling process?',
        correctAnswers: ['fork', 'fork()'],
        points: 15,
        explanation: 'The fork() system call creates a child process identical to the parent.',
      },
      {
        id: 'q5',
        type: 'essay',
        prompt: 'Briefly explain the difference between a race condition and a deadlock in multi-threaded programming. How does a mutex prevent race conditions?',
        correctAnswers: [],
        points: 15,
        explanation: 'A race condition occurs when concurrent threads access shared data without synchronization, making output dependent on timing. Deadlock occurs when threads are blocked waiting indefinitely on circular resource dependencies. A mutex enforces mutual exclusion so only one thread accesses the critical section at a time.',
      },
    ],
  },
  {
    id: 'exam-bio210-quiz',
    title: 'BIO 210: Molecular Genetics & CRISPR Technology Quiz',
    courseCode: 'BIO-210',
    description: 'Assessment on DNA replication forks, RNA transcription regulation, CRISPR-Cas9 mechanism, and single nucleotide polymorphisms.',
    durationMinutes: 30,
    totalPoints: 50,
    passingPercentage: 60,
    accessCode: 'BIO-4402',
    status: 'active',
    createdAt: new Date(Date.now() - 3600000 * 48).toISOString(),
    professorName: 'Prof. Marcus Vance',
    professorEmail: 'mvance@university.edu',
    securitySettings: {
      fullscreenEnforced: true,
      webcamRequired: true,
      audioMonitoring: true,
      blockCopyPaste: true,
      blockDevToolsAndShortcuts: true,
      tabSwitchDetection: true,
      faceTracking: true,
      gazeDetection: false,
      multiplePersonDetection: true,
      maxViolationsAllowed: 4,
      randomizeQuestions: false,
      randomizeOptions: true,
      requirePasscode: false,
      strictAutoSubmit: true,
    },
    sharingSettings: {
      publicLinkEnabled: true,
      accessCodeEnabled: true,
      qrCodeEnabled: true,
      embedCodeEnabled: true,
      customSlug: 'bio210-genetics-quiz',
    },
    questions: [
      {
        id: 'bq1',
        type: 'multiple_choice',
        prompt: 'What enzyme is primarily responsible for synthesizing the new strand of DNA by adding nucleotides in the 5\' to 3\' direction during replication?',
        options: [
          { id: 'b_opt_a', text: 'DNA Helicase' },
          { id: 'b_opt_b', text: 'DNA Polymerase III' },
          { id: 'b_opt_c', text: 'RNA Primase' },
          { id: 'b_opt_d', text: 'DNA Ligase' },
        ],
        correctAnswers: ['b_opt_b'],
        points: 25,
        explanation: 'DNA Polymerase III synthesizes the leading and lagging strands in prokaryotes from 5\' to 3\'.',
      },
      {
        id: 'bq2',
        type: 'multiple_choice',
        prompt: 'What specific sequence motif does Streptococcus pyogenes Cas9 require directly downstream of the target DNA sequence to cleave?',
        options: [
          { id: 'b_opt_a', text: 'TATA Box' },
          { id: 'b_opt_b', text: 'PAM (NGG) Sequence' },
          { id: 'b_opt_c', text: 'Poly-A tail' },
          { id: 'b_opt_d', text: 'Kozak consensus sequence' },
        ],
        correctAnswers: ['b_opt_b'],
        points: 25,
        explanation: 'SpCas9 requires a Protospacer Adjacent Motif (PAM), specifically 5\'-NGG-3\', immediately following the target protospacer.',
      },
    ],
  },
];

export const INITIAL_STUDENT_SESSIONS: StudentSession[] = [
  {
    sessionId: 'sess-emma-101',
    examId: 'exam-cs350-midterm',
    studentName: 'Emma Watson',
    studentEmail: 'e.watson@student.edu',
    studentId: 'STU-99214',
    status: 'in_progress',
    startedAt: new Date(Date.now() - 1200000).toISOString(),
    timeRemainingSeconds: 1500,
    currentQuestionIndex: 3,
    answers: {
      q1: 'opt_c',
      q2: ['opt_a', 'opt_b'],
      q3: 'opt_b',
    },
    flaggedQuestions: ['q2'],
    violations: [],
    integrityScore: 100,
    faceStatus: 'normal',
    audioDecibels: 22,
    audioAlert: false,
    isOnline: true,
    lastHeartbeat: new Date().toISOString(),
    proctorWarnings: [],
  },
  {
    sessionId: 'sess-lucas-102',
    examId: 'exam-cs350-midterm',
    studentName: 'Lucas Vance',
    studentEmail: 'l.vance@student.edu',
    studentId: 'STU-88341',
    status: 'in_progress',
    startedAt: new Date(Date.now() - 1400000).toISOString(),
    timeRemainingSeconds: 1300,
    currentQuestionIndex: 2,
    answers: {
      q1: 'opt_c',
      q2: ['opt_a'],
    },
    flaggedQuestions: [],
    violations: [
      {
        id: 'viol-lv-1',
        timestamp: new Date(Date.now() - 600000).toISOString(),
        type: 'tab_switch',
        severity: 'medium',
        description: 'Student unfocused exam tab (switched to another window / application for 4 seconds)',
      },
      {
        id: 'viol-lv-2',
        timestamp: new Date(Date.now() - 250000).toISOString(),
        type: 'audio_spike',
        severity: 'low',
        description: 'Sudden high ambient noise spike (72 dB detected by microphone)',
      },
    ],
    integrityScore: 88,
    faceStatus: 'away',
    audioDecibels: 48,
    audioAlert: false,
    isOnline: true,
    lastHeartbeat: new Date().toISOString(),
    proctorWarnings: ['Please remain focused on your screen.'],
  },
  {
    sessionId: 'sess-sophia-103',
    examId: 'exam-cs350-midterm',
    studentName: 'Sophia Chen',
    studentEmail: 's.chen@student.edu',
    studentId: 'STU-77412',
    status: 'in_progress',
    startedAt: new Date(Date.now() - 1800000).toISOString(),
    timeRemainingSeconds: 900,
    currentQuestionIndex: 4,
    answers: {
      q1: 'opt_c',
      q2: ['opt_a', 'opt_b'],
      q3: 'opt_b',
      q4: 'fork',
    },
    flaggedQuestions: [],
    violations: [
      {
        id: 'viol-sc-1',
        timestamp: new Date(Date.now() - 800000).toISOString(),
        type: 'looking_away',
        severity: 'low',
        description: 'Student gaze shifted outside of display monitor area for > 5 seconds',
      },
    ],
    integrityScore: 95,
    faceStatus: 'normal',
    audioDecibels: 18,
    audioAlert: false,
    isOnline: true,
    lastHeartbeat: new Date().toISOString(),
    proctorWarnings: [],
  },
  {
    sessionId: 'sess-david-104',
    examId: 'exam-cs350-midterm',
    studentName: 'David Miller',
    studentEmail: 'd.miller@student.edu',
    studentId: 'STU-44109',
    status: 'flagged',
    startedAt: new Date(Date.now() - 2100000).toISOString(),
    timeRemainingSeconds: 600,
    currentQuestionIndex: 2,
    answers: {
      q1: 'opt_b',
      q2: ['opt_c'],
    },
    flaggedQuestions: ['q1'],
    violations: [
      {
        id: 'viol-dm-1',
        timestamp: new Date(Date.now() - 1500000).toISOString(),
        type: 'fullscreen_exit',
        severity: 'high',
        description: 'Exited secure full-screen mode without authorization',
      },
      {
        id: 'viol-dm-2',
        timestamp: new Date(Date.now() - 1100000).toISOString(),
        type: 'paste_attempt',
        severity: 'high',
        description: 'Attempted to paste clipboard content into question input field (blocked)',
      },
      {
        id: 'viol-dm-3',
        timestamp: new Date(Date.now() - 700000).toISOString(),
        type: 'tab_switch',
        severity: 'medium',
        description: 'Navigated away from browser tab for 12 seconds',
      },
      {
        id: 'viol-dm-4',
        timestamp: new Date(Date.now() - 300000).toISOString(),
        type: 'multiple_faces',
        severity: 'critical',
        description: 'AI Camera analysis detected multiple individuals in the webcam frame',
      },
    ],
    integrityScore: 42,
    faceStatus: 'multiple',
    audioDecibels: 64,
    audioAlert: true,
    isOnline: true,
    lastHeartbeat: new Date().toISOString(),
    proctorWarnings: [
      'Warning: Secondary individual detected in webcam frame.',
      'Notice: Multiple high-risk anti-cheat violations recorded. One more violation will trigger immediate auto-disqualification.',
    ],
  },
];
